server:
  port: '8091'
spring:
  datasource:
    username: madu00
    url: jdbc:mysql://localhost:3306/pizza-creed?createDatabaseIfNotExist=true
    password: madu@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: 'false'
logging:
  level:
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG